---
sidebar: sidebar 
permalink: integrations/dashboard-overview.html 
keywords: Keystone, Digital Advisor, keystone-aiq, aiq, BlueXP, Keystone dashboard, NetApp Console, Console 
summary: Como assinante do NetApp Keystone STaaS, você pode obter uma visão geral de suas assinaturas no NetApp Console ou no Digital Advisor. 
---
= Saiba mais sobre o painel Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O painel do Keystone é a sua solução ideal para monitorar, analisar e gerenciar suas assinaturas do Keystone com eficiência. Por meio dele, você pode atingir os seguintes objetivos:

* *Monitorar detalhes da assinatura*: visualize informações detalhadas sobre suas assinaturas do Keystone, incluindo níveis de serviço de desempenho, uso de capacidade, ativos e alertas.
* *Acompanhe o uso da capacidade e gere relatórios*: acompanhe o uso atual e histórico da capacidade e gere relatórios para analisar dados de assinatura e tomar decisões informadas.
* *Ver cronograma de assinaturas*: Mantenha-se informado sobre datas e eventos importantes monitorando o cronograma de suas assinaturas.
* *Gerenciar assinaturas*: envie solicitações para modificar níveis de serviço de desempenho ou outros parâmetros de assinatura conforme suas necessidades mudam.
* *Analise volumes e objetos*: obtenha insights detalhados sobre os volumes e objetos de suas assinaturas, incluindo sua capacidade nos níveis de volume e objeto.




== Acesse o painel do Keystone

Você pode acessar o painel do Keystone através de:

* * Console NetApp *: acesse o painel em *Armazenamento > Keystone > Visão geral* no Console. Para saber mais, consultelink:../integrations/keystone-console.html["Painel Keystone no NetApp Console"^] .
* *Active IQ Digital Advisor* (também conhecido como Digital Advisor): Acesse o painel em *Geral > Assinaturas Keystone* no Digital Advisor. Para saber mais, link:../integrations/keystone-aiq.html["Painel Keystone no Digital Advisor"^]consulte .




== Sobre o NetApp Console

O Keystone pode ser acessado pelo NetApp Console.

O NetApp Console fornece gerenciamento centralizado de serviços de armazenamento e dados da NetApp em ambientes locais e na nuvem em escala empresarial. O Console é necessário para acessar e usar os serviços de dados do NetApp . Como uma interface de gerenciamento, ele permite que você gerencie muitos recursos de armazenamento a partir de uma única interface. Os administradores do console podem controlar o acesso ao armazenamento e aos serviços de todos os sistemas da empresa.

Você não precisa de uma licença ou assinatura para começar a usar o Console e só incorrerá em cobranças quando precisar implantar agentes do Console na sua nuvem para garantir a conectividade com seus sistemas de armazenamento ou serviços de dados da NetApp . No entanto, alguns serviços de dados da NetApp acessíveis pelo Console são licenciados ou baseados em assinatura.

Saiba mais sobre olink:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["Console NetApp"^] .

Observe o seguinte:

* Embora o Console e o Digital Advisor ofereçam alguns recursos exclusivos, o Console fornece funcionalidade administrativa para o Keystone, permitindo que você gerencie assinaturas e faça os ajustes necessários.
* Você deve ter a função *Administrador do Keystone * atribuída para modificar assinaturas. Para saber mais, consultelink:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console"^] .
* O Digital Advisor é integrado ao Console, permitindo que você acesse todos os recursos do Digital Advisor , incluindo o painel do Keystone , diretamente do Console. Para saber mais, consultelink:https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-console.html#netapp-console["Integração do Digital Advisor com o NetApp Console"^] .




== Recursos do Keystone no NetApp Console e no Digital Advisor

A tabela a seguir mostra a disponibilidade de recursos no NetApp Console e no Digital Advisor, ajudando você a identificar rapidamente a plataforma certa para suas necessidades:

|===


| *Recurso* | * Console NetApp * | *Consultor Digital* 


 a| 
link:../integrations/subscriptions-tab.html["Ver detalhes da sua assinatura"]
| Sim | Sim 


 a| 
link:../integrations/current-usage-tab.html["Monitore o uso atual e histórico da capacidade"]
| Sim | Sim 


 a| 
link:../integrations/subscription-timeline.html["Acompanhe o cronograma de assinatura"]
| Sim | Não 


 a| 
link:../integrations/assets-tab.html["Ver ativos associados a uma assinatura Keystone"]
| Sim | Sim 


| link:../integrations/assets.html["Visualizar ativos em várias assinaturas do Keystone"] | Sim | Não 


 a| 
link:../integrations/monitoring-alerts.html["Visualizar e gerenciar alertas e monitores"]
| Sim | Não 


 a| 
link:../integrations/modify-subscription.html["Modifique suas assinaturas"] (somente para administradores do Keystone)
| Sim | Não 


 a| 
link:../integrations/options.html#generate-reports-from-netapp-console-or-digital-advisor["Gerar relatórios"]
| Sim | Sim 


 a| 
link:../integrations/volumes-objects-tab.html["Ver detalhes de volumes e objetos"]
| Sim | Sim 


 a| 
link:../integrations/performance-tab.html["Ver métricas de performance"]
| Não | Sim 
|===
*Informações relacionadas*

* link:../integrations/dashboard-access.html["Comece a usar o painel do Keystone"]
* link:../integrations/keystone-console.html["Painel Keystone no NetApp Console"]
* link:..//integrations/keystone-aiq.html["Painel Keystone no Digital Advisor"]

