---
sidebar: sidebar 
permalink: integrations/keystone-cm.html 
keywords: Keystone-BlueXP 
summary: Se você adquiriu um serviço de nuvem com sua assinatura do NetApp Keystone, poderá acessar e gerenciar esses serviços por meio do BlueXP . 
---
= Saiba mais sobre o Keystone e o BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O NetApp BlueXP  é um painel de controle único para criar, proteger e governar dados em ambientes locais e de nuvem. Se você adquirir um serviço de nuvem na sua subscrição do NetApp Keystone, poderá acessar e gerenciar esses serviços por meio do BlueXP .

O dashboard do consultor digital do BlueXP  oferece uma visualização gráfica e funcionalidades de detalhamento para monitorar o uso da assinatura do Keystone e gerar relatórios. Para obter mais informações sobre o painel do Digital Advisor e o Keystone, link:../integrations/aiq-keystone-details.html["Painel e geração de relatórios do Keystone Subscription"]consulte .

Como cliente do Keystone, se você tem uma subscrição do Cloud Volumes ONTAP, use os serviços do Keystone para cobrar o uso do Cloud Volumes ONTAP e visualizar os detalhes de cobrança e consumo por meio do BlueXP .

Para isso, você deve criar uma ou mais contas do BlueXP  e vinculá-las à sua conta do Keystone. Enquanto você compra um serviço de nuvem com o Keystone, você precisa fornecer os detalhes de suas contas do BlueXP  ao seu Gerenciador de sucesso do Keystone (KSM). Isso possibilita a medição e o carregamento adequados do uso do serviço de nuvem com a subscrição do Keystone.

Para obter mais informações sobre o Keystone e o BlueXP , consulte os links a seguir nos documentos do BlueXP :

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html#keystone-flex-subscription["Inscrição no Keystone"^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-keystone.html["Gerenciar as assinaturas do Keystone"^]

