---
settings:
  name: Keystone
  release_notes_autogen:
    release_notes_repo: console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    release_notes_autogen:
      release_notes_repo: console-relnotes
  versions:
  - version-number: '3.0'
    url: "/keystone-staas"
  - version-number: '2.0'
    url: "/keystone-staas-2"
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos do Keystone
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: Novidades do Keystone STaaS
      url: "/whats-new.html"
    - title: Problemas corrigidos
      url: "/release-notes/fixed-issues.html"
    - title: Problemas conhecidos
      url: "/release-notes/known-issues.html"
    - title: Limitações conhecidas
      url: "/release-notes/known-limitations.html"
  - title: Comece agora
    entries:
    - title: Saiba mais sobre o Keystone STaaS
      url: "/concepts/overview.html"
    - title: Infraestrutura do Keystone
      url: "/concepts/infra.html"
    - title: Keystone Collector
      url: "/installation/installation-overview.html"
    - title: Componentes
      url: "/concepts/components.html"
    - title: Fluxo de dados
      url: "/concepts/data-flow.html"
    - title: Modelos operacionais
      url: "/concepts/operational-models.html"
  - title: Configurar o Keystone
    entries:
    - title: Requisitos
      entries:
      - title: Infraestrutura virtual
        url: "/installation/vapp-prereqs.html"
      - title: Linux
        url: "/installation/linux-prereqs.html"
      - title: ONTAP e StorageGRID
        url: "/installation/addl-req.html"
    - title: Instale o Keystone Collector
      entries:
      - title: Implante no VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Instale no Linux
        url: "/installation/linux-installation.html"
      - title: Validação automática do software Keystone
        url: "/installation/validation.html"
    - title: Configure o Keystone Collector
      url: "/installation/configuration.html"
    - title: Instale o ITOM Collector
      entries:
      - title: Prepare-se para a instalação
        url: "/installation/itom-prereqs.html"
      - title: Instale no Linux
        url: "/installation/install-itom-linux.html"
      - title: Instale no Windows
        url: "/installation/install-itom-windows.html"
    - title: Configurar o AutoSupport
      url: "/installation/asup-config.html"
    - title: Monitorar e atualizar
      entries:
      - title: Monitore a integridade do Keystone Collector
        url: "/installation/monitor-health.html"
      - title: Atualize o Keystone Collector
        url: "/installation/upgrade.html"
    - title: Segurança do Keystone Collector
      url: "/installation/security.html"
    - title: Dados coletados para faturamento
      url: "/installation/data-collection.html"
    - title: Keystone em modo privado
      entries:
      - title: Visão geral
        url: "/dark-sites/overview.html"
      - title: Prepare-se para a instalação
        url: "/dark-sites/requirements.html"
      - title: Instale o Keystone Collector
        url: "/dark-sites/install-collector.html"
      - title: Configure o Keystone Collector
        url: "/dark-sites/configure-collector.html"
      - title: Monitore a integridade do Keystone Collector
        url: "/dark-sites/monitor.html"
  - title: Gerenciar e monitorar assinaturas do Keystone
    entries:
    - title: Entenda o painel do Keystone
      entries:
      - title: Saiba mais sobre o painel Keystone
        url: "/integrations/dashboard-overview.html"
      - title: Comece a usar o painel do Keystone
        url: "/integrations/dashboard-access.html"
      - title: Painel Keystone no NetApp Console
        url: "/integrations/keystone-console.html"
      - title: Painel Keystone no Digital Advisor
        url: "/integrations/keystone-aiq.html"
      - title: Pesquise dados, gere relatórios e visualize alertas
        url: "/integrations/options.html"
    - title: Ver insights de assinatura
      entries:
      - title: Ver detalhes da sua assinatura
        url: "/integrations/subscriptions-tab.html"
      - title: Veja os detalhes do seu consumo atual
        url: "/integrations/current-usage-tab.html"
      - title: Veja as tendências de consumo
        url: "/integrations/consumption-tab.html"
      - title: Veja o cronograma da sua assinatura
        url: "/integrations/subscription-timeline.html"
    - title: Ver ativos
      entries:
      - title: Exibir ativos associados a uma assinatura
        url: "/integrations/assets-tab.html"
      - title: Visualizar ativos em várias assinaturas
        url: "/integrations/assets.html"
    - title: Visualizar e gerenciar alertas e monitores
      entries:
      - title: Visualizar e gerenciar alertas
        url: "/integrations/monitoring-alerts.html"
      - title: Visualizar e criar monitores de alerta
        url: "/integrations/monitoring-alert-monitors.html"
    - title: Modifique suas assinaturas
      url: "/integrations/modify-subscription.html"
    - title: Visualize sua solicitação de serviço
      url: "/integrations/administration-tab.html"
    - title: Exibir volumes e detalhes de armazenamento de objetos
      url: "/integrations/volumes-objects-tab.html"
    - title: Ver métricas de performance
      url: "/integrations/performance-tab.html"
  - title: Conceitos
    entries:
    - title: Serviços Keystone STaaS
      entries:
      - title: Métricas e definições
        url: "/concepts/metrics.html"
      - title: Armazenamento suportado
        url: "/concepts/supported-storage-services.html"
      - title: Capacidade suportada
        url: "/concepts/supported-storage-capacity.html"
      - title: Níveis de serviço de desempenho
        url: "/concepts/service-levels.html"
      - title: Requisitos de capacidade para níveis de serviço de desempenho
        url: "/concepts/capacity-requirements.html"
    - title: Serviços complementares
      entries:
      - title: Opções de capacidade de burst
        url: "/concepts/burst-capacity.html"
      - title: Insights da infraestrutura de dados
        url: "/concepts/data-infra-insights.html"
      - title: Categorização de dados
        url: "/concepts/data-tiering.html"
      - title: Componentes não retornáveis, não voláteis e SnapLock Compliance
        url: "/concepts/nrnvc.html"
      - title: U.S. Protected Support (USPS)
        url: "/concepts/usps.html"
    - title: SLO do Keystone STaaS
      entries:
      - title: Disponibilidade
        url: "/concepts/sla-availability.html"
      - title: Desempenho
        url: "/concepts/sla-performance.html"
      - title: Sustentabilidade
        url: "/concepts/sla-sustainability.html"
      - title: Garantia de recuperação de ransomware
        url: "/concepts/sla-ransomware.html"
    - title: Faturamento
      entries:
      - title: Preços do Keystone
        url: "/concepts/pricing.html"
      - title: Cobrança baseada na capacidade comprometida
        url: "/concepts/committed-capacity-billing.html"
      - title: Medição baseada na capacidade consumida
        url: "/concepts/consumed-capacity-billing.html"
      - title: Cobrança baseada no consumo de expansões sazonais
        url: "/concepts/burst-consumption-billing.html"
      - title: Cenários diversos para faturamento do Keystone
        url: "/concepts/misc-volume-billing.html"
      - title: Horários de faturamento
        url: "/concepts/billing-schedules.html"
  - title: Acesse o Keystone a partir da API REST do Digital Advisor
    entries:
    - title: Comece a usar a API REST do Digital Advisor para recuperar dados do Keystone
      url: "/rest-api/retrieve-keystone-data-with-digital-advisor-rest-api.html"
    - title: Gerar tokens de atualização e acesso
      url: "/rest-api/generate-tokens.html"
    - title: Obtenha uma lista de todos os clientes usando a API REST do Digital Advisor
      url: "/rest-api/get-customer-list.html"
    - title: Obtenha assinaturas de clientes usando a API REST do Digital Advisor
      url: "/rest-api/get-customer-subscriptions.html"
    - title: Obtenha detalhes do consumo do cliente usando a API REST do Digital Advisor
      url: "/rest-api/get-customer-consumption.html"
  - title: Serviços de subscrição Keystone versão 1
    url: "/subscription-services-v1.html"
  - title: Obtenha ajuda com o Keystone
    url: "/concepts/gssc.html"
  - title: Avisos legais
    url: "/legal-notices.html"
