---
sidebar: sidebar 
permalink: subscription-services-v1.html 
keywords: Keystone Flex Subscriptions, kfs v1, keystone legacy, Keystone subscription services version 1 
summary: Keystone STaaS em serviços Keystone Flex Subscription 
---
= Serviços de assinatura do Keystone | versão 1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Keystone STaaS foi precedido pelos serviços de subscrição do Keystone (anteriormente conhecidos como serviços de subscrição Keystone Flex).

Embora a navegação das duas ofertas seja semelhante no link:./integrations/aiq-keystone-details.html["Painel do Keystone"^], os serviços de assinatura do Keystone diferem dos STaaS no que diz respeito aos níveis de serviço, oferta de serviço e princípios de cobrança. A partir de abril de 2024, a NetApp mantém e publica documentação somente para o Keystone STaaS. Se você ainda estiver usando os serviços de assinatura do Keystone, entre em Contato com seu KSM para obter suporte na migração para o Keystone STaaS. Se necessário, você pode acessar uma versão em PDF da documentação dos serviços de assinatura do Keystone aqui:

* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide.pdf["Inglês"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-ja-jp.pdf["Japonês"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-ko-kr.pdf["Coreano"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-zh-cn.pdf["Chinês (simplificado)"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-zh-tw.pdf["Chinês (tradicional)"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-de-de.pdf["Alemão"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-es-es.pdf["Espanhol"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-fr-fr.pdf["Francês"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-it-it.pdf["Italiano"^]

