---
sidebar: sidebar 
permalink: rest-api/get-customer-consumption.html 
keywords: api, consumption, subscriptions, customerID, keystone, Digital Advisor 
summary: A API REST do Digital Advisor recupera os detalhes de consumo atuais de todas as assinaturas associadas ao customerId fornecido. 
---
= Obtenha detalhes do consumo do cliente usando a API REST do Digital Advisor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta API recupera os detalhes de consumo atuais de todas as assinaturas associadas ao customerId dado.

*Pedido:*

[cols="24%,76%"]
|===


| *Método* | OBTER 


| *Endpoint* | `https://api.activeiq.netapp.com/v1/keystone/customer/consumption-details` 


| *Parâmetros*  a| 
* tipo: "cliente"
* id: <customer-id>




| *Cabeçalhos*  a| 
* aceitar: aplicação/json
* AutorizaçãoToken: <access_key>


|===
*Resposta:* a API responderá com um objeto JSON contendo uma lista de todas as assinaturas com as métricas de uso do serviço atuais para o cliente determinado. Aqui está um exemplo de resposta:

[listing]
----
{
"result":  {
"returned_records": "string",
"records": [
{
"subscription":  {
"account_name": "string",
"number": "string",
"start_date": "string",
"end_date": "string"
},
"service_levels": [
{
"name": "string",
"committed_tib": "string",
"consumed_tib": "string",
"consumed_timestamp_utc": "string",
"burst_tib": "string",
"accrued_burst_tib": "string"
}
]
}
],
"request_id": "string",
"response_time": "string"
}
}
----
*Código de status*: 200 – solicitação bem-sucedida

*Curl exemplo*:

[source, curl]
----
curl -X 'GET' \ 'https://api.activeiq.netapp.com/v1/keystone/customer/consumption-details?type=customer&id=<customerID>' \ -H 'accept: application/json' \ -H 'authorizationToken: <access-key>'
----


== Obtenha os detalhes históricos de consumo de um cliente

Esta API recupera os detalhes do histórico de consumo de todas as assinaturas associadas ao customerId dado de acordo com o intervalo de tempo especificado.

*Pedido:*

[cols="24%,76%"]
|===


| *Método* | OBTER 


| *Endpoint* | `https://api.activeiq.netapp.com/v1/keystone/customer/historical-consumption-details` 


| *Parâmetros*  a| 
* tipo: "cliente"
* id: <customer-id>
* From_date_utc: [Data de início (no formato RFC3339)]>
* To_date_utc: [End date(in RFC3339 format)>




| *Cabeçalhos*  a| 
* aceitar: aplicação/json
* AutorizaçãoToken: <access_key>


|===
*Resposta:*

A API responderá com um objeto JSON contendo uma lista de todas as assinaturas com as métricas históricas de uso do serviço para o cliente determinado no intervalo de tempo selecionado. Aqui está um exemplo de resposta:

[listing]
----
{
"results":  {
"returned_records": 0,
"records": [
{
"subscription":  {
"account_name": "string",
"number": "string",
"start_date": "2023-08-24T14:15:22Z",
"end_date": "2023-08-24T14:15:22Z"
},
"service_levels": [
{
"name": "string",
"historical_consumption": [
{
"committed_tib": 0,
"consumed_tib": 0,
"timestamp_utc": "2023-08-24T14:15:22Z",
"burst_tib": 0,
"accrued_burst_tib": 0,
"is_invoiced": true
}
]
}
]
}
],
"request_parameters":  {
"from_date_utc": "2023-08-24",
"to_date_utc": "2023-08-24",
"customer_id": "string"
},
"request_id": "string",
"response_time": "string",
"customer":  {
"name": "string",
"id": "string"
}
}
}
----
*Código de status*: 200 – solicitação bem-sucedida

*Curl exemplo*:

[source, curl]
----
curl -X 'GET' \ 'https://api.activeiq-stg.netapp.com/v1/keystone/customer/historical-consumption-details? type=customer&id=<customerID>&from_date_utc=2023-08-24T14%3A15%3A22Z&t _date_utc=2023-08-24T14%3A15%3A22Z' \ -H 'accept: application/json' \ -H 'authorizationToken: <access-key>'
----