= Novas colunas na guia Volumes em clusters
:allow-uri-read: 


Novos aprimoramentos no painel do Keystone no NetApp Console:



[[new-columns-in-the-volumes-in-clusters-tab]]
=== Novas colunas na guia Volumes em clusters

Três novas colunas, *Dados quentes*, *Camada fria (%)* e *Camada quente (%)*, foram adicionadas à guia *Volumes em clusters* em *Ativos*. Para saber mais, consulte  https://docs.netapp.com/us-en/keystone-staas/integrations/assets-tab.html["Ver ativos associados a uma assinatura Keystone"] e  https://docs.netapp.com/us-en/keystone-staas/integrations/assets.html["Visualize ativos em suas assinaturas Keystone"].



[[invoiced-uninvoiced-and-provisional-burst-usage-in-consumption-trend]]
=== Consumo faturado, não faturado e provisório em picos de demanda na tendência de consumo

O gráfico de faturamento acumulado de picos na aba *Tendência de consumo* agora exibe o uso de picos faturados, não faturados e provisórios. Para saber mais, consulte https://docs.netapp.com/us-en/keystone-staas/integrations/consumption-tab.html#view-accrued-burst["Ver explosão acumulada"].



[[enhancements-to-the-monitoring-view]]
=== Melhorias na visualização de monitoring

A visualização *Monitoring* inclui as seguintes atualizações:

* *Aba de alertas*: A coluna *Alerta* foi renomeada para *Tipo e condição do alerta*. Agora você também pode usar o ícone de reticências ao lado da coluna *Status* para editar um alerta, adicionar uma nota ou visualizar os detalhes do alerta.
* *Aba Alert monitors*: A coluna *Condition* foi renomeada para *Monitor type & condition*.


Para saber mais, consulte  https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alerts.html["Visualizar e gerenciar alertas para assinaturas do Keystone"] e  https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html["Visualize e crie monitores de alerta para assinaturas do Keystone"].
