---
sidebar: sidebar 
permalink: concepts/billing-schedules.html 
keywords: billing schedules, schedule for payment 
summary: As assinaturas do Keystone STaaS são cobradas mensalmente, trimestralmente, semestralmente ou anualmente. 
---
= Horários de faturamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
As assinaturas do Keystone STaaS são cobradas mensalmente, trimestralmente, semestralmente ou anualmente.



== Cobrança mensal

As faturas são enviadas mensalmente. Para o mês em que os serviços estão disponíveis, uma fatura é enviada no mês seguinte. Por exemplo, a fatura dos serviços que utilizou em Janeiro é entregue no início de Fevereiro. Esta fatura inclui os encargos para a capacidade comprometida e, se aplicável, qualquer uso de expansões sazonais.



== Faturamento trimestral, semestral e anual

Para faturamento trimestral, semestral e anual, o processo é semelhante, com pequenas variações no tempo:

* *Faturamento trimestral*: Uma fatura é gerada no início de cada trimestre de assinatura para o pagamento mínimo da capacidade comprometida. Outra fatura é enviada no final do trimestre para qualquer uso excessivo acumulado.
* *Faturamento semestral*: Uma fatura é gerada no início de cada seis meses para o pagamento mínimo da capacidade comprometida.  Outra fatura é enviada no final de cada trimestre para qualquer uso excessivo acumulado.
* *Faturamento anual*: Uma fatura é gerada no início de cada ano de assinatura para o pagamento mínimo da capacidade comprometida.  Outra fatura é enviada no final de cada trimestre para qualquer uso excessivo acumulado.


Para cobranças trimestrais, semestrais e anuais, se a capacidade comprometida for alterada durante uma assinatura, uma fatura será enviada no mesmo dia para os pagamentos mínimos proporcionais ao restante do ano de assinatura.  O faturamento é calculado a partir do dia em que a alteração na capacidade comprometida se torna efetiva.
