---
sidebar: sidebar 
permalink: concepts/billing-schedules.html 
keywords: billing schedules, schedule for payment 
summary: As assinaturas do Keystone STaaS são cobradas mensalmente e anualmente. 
---
= Horários de faturamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
As assinaturas do Keystone STaaS são cobradas mensalmente e anualmente.



== Cobrança mensal

As faturas são enviadas mensalmente. Para o mês em que os serviços estão disponíveis, uma fatura é enviada no mês seguinte. Por exemplo, a fatura dos serviços que utilizou em Janeiro é entregue no início de Fevereiro. Esta fatura inclui os encargos para a capacidade comprometida e, se aplicável, qualquer uso de expansões sazonais.



== Faturamento anual

Uma fatura é gerada no início de cada ano de assinatura para o pagamento mínimo da capacidade comprometida. Ele é gerado na data de início da assinatura. Outra fatura é enviada no final de um trimestre de subscrição, somando as taxas aplicáveis de qualquer utilização de expansões sazonais acumuladas nesse trimestre. Se a capacidade comprometida for alterada durante uma assinatura, uma fatura será enviada no mesmo dia para os pagamentos mínimos pré-pagos para o resto do ano de assinatura. A cobrança é calculada a partir do dia em que a alteração na capacidade comprometida é efetiva.
