---
sidebar: sidebar 
permalink: concepts/burst-consumption-billing.html 
keywords: burst consumption billing 
summary: A cobrança do Keystone STaaS é baseada na capacidade de expansão sazonal, que é a capacidade consumida por você, além da capacidade comprometida da sua assinatura. 
---
= Entenda a cobrança de consumo em rajadas da Keystone.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A cobrança do Keystone STaaS é baseada em _capacidade de expansão sazonal_, que é a capacidade consumida por você, além da capacidade comprometida da sua assinatura.

Seu limite de explosão é determinado e especificado no contrato do Keystone. Por padrão, ele é definido em 20% acima da capacidade comprometida. Você também tem a opção de escolher limites de capacidade de pico de 40% ou 60% da capacidade comprometida. Para saber mais, link:../concepts/burst-capacity.html["Opções de aumento da capacidade de burst"]consulte .

Capacidade comprometida é a capacidade comprometida com você durante a compra da assinatura. A capacidade comprometida e a capacidade de pico são medidas por nível de serviço de desempenho. A capacidade consumida é a capacidade que seus workloads realmente usam.

Quando a capacidade consumida é maior que a capacidade comprometida para um nível de serviço de desempenho, o consumo de pico é registrado e cobrado adequadamente. O uso acima da capacidade de explosão é indicado como "acima do limite de explosão".

Este processo ocorre para cada Registro de consumo gerado. O consumo de expansões sazonais, portanto, é um reflexo da quantidade e da posse de suas capacidades sobreconsumidas, além de suas capacidades comprometidas. Para saber mais, link:../integrations/consumption-tab.html["Veja as tendências de consumo das suas assinaturas Keystone"]consulte .

Para obter informações sobre as diferentes capacidades suportadas no Keystone, consulte link:../concepts/supported-storage-capacity.html["Tipos de capacidade de storage em Keystone"].
