---
sidebar: sidebar 
permalink: concepts/consumed-capacity-billing.html 
keywords: consumed capacity billing, billing and consumed capacity 
summary: A capacidade consumida é a capacidade que seus workloads realmente usam durante o uso do serviço. 
---
= Entenda a medição da capacidade consumida da Keystone.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O Keystone STaaS tem medição com base na capacidade consumida por você durante o uso do serviço. A capacidade consumida é a capacidade que seus workloads realmente usam.

Como parte da implantação do serviço do Keystone, o NetApp monitora e mede continuamente o consumo do serviço. Pelo menos uma vez em cada cinco minutos, um Registro de consumo é gerado pelo sistema, detalhando a capacidade consumida atual para sua assinatura. Esses Registros são agregados durante o período de faturamento para gerar faturas e relatórios de uso.

Para obter informações sobre as diferentes capacidades suportadas no Keystone, consulte link:../concepts/supported-storage-capacity.html["Tipos de capacidade de storage em Keystone"].
