---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: O serviço complementar de categorização de dados identifica os dados usados com menos frequência e categoriza-os em storage com suporte. 
---
= Saiba mais sobre categorização de dados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Os serviços padrão do Keystone STaaS para storage de arquivo e de bloco incluem funcionalidades de disposição em camadas que identificam dados usados com menos frequência e categorizam-no no storage frio NetApp compatível com STaaS do Keystone. Você pode usar a disposição de dados em categorias como serviço complementar se quiser categorizar seus dados inativos em qualquer storage que não seja NetApp compatível com Keystone STaaS.

Para obter informações sobre serviços padrão e complementares, link:../concepts/supported-storage-services.html["Serviços Keystone STaaS"]consulte . Para obter informações sobre os níveis de serviço de desempenho, consulte link:../concepts/service-levels.html["Níveis de serviço de desempenho em Keystone"] .


NOTE: O serviço complementar de camadas é necessário somente quando os dados são colocados em camadas em qualquer armazenamento não NetApp , como Amazon Web Services (AWS) S3, Azure Blob, Google Cloud Platform (GCP) e outros armazenamentos de objetos de terceiros compatíveis com S3 e com suporte do Keystone STaaS.

A funcionalidade de disposição em camadas utiliza a tecnologia NetApp FabricPool que permite a disposição automatizada em camadas de storage de objetos no local e fora dela.

O serviço de hierarquização de dados complementar permite a hierarquização dos níveis Extreme, Premium, Performance, Standard e Value para um destino de armazenamento de objetos. A proporção de dados quentes e frios a serem hierarquizados não é fixa, e cada nível é medido e faturado separadamente.

Por exemplo, se o destino para a camada de storage frio for:

* Nível de valor do Keystone STaaS, nível de objeto do Keystone STaaS StorageGRID ou grade StorageGRID Webscale (SGWS) existente (de propriedade do cliente) - Não há custo adicional; faz parte do serviço padrão.
* Storage de objetos de terceiros com suporte para nuvem pública (AWS, Azure, Google) ou Keystone STaaS – há uma cobrança adicional pela capacidade de dados que é categorizada no destino de storage frio.


As cobranças por serviços de disposição em camadas complementares se aplicam a todo o prazo de assinatura.


NOTE: Os serviços de computação, armazenamento e rede baseados em hiperescalador exigidos pelo Cloud Volumes ONTAP não são fornecidos pela NetApp como parte das assinaturas do Keystone STaaS; esses serviços precisam ser adquiridos diretamente de provedores de serviços de nuvem em hiperescalador.

*Informações relacionadas*

link:https://kb.netapp.com/hybrid/Keystone/AIQ_Dashboard/How_to_approximate_Keystone_Consumption_with_Data_Tiering_(FabricPool)_through_the_ONTAP_cli["Como aproximado o consumo do Keystone com a disposição de dados em categorias (FabricPool) usando a CLI do ONTAP"^]
