---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Keystone support, service request, support ticket 
summary: Se precisar de ajuda, entre em Contato com a equipe de suporte da NetApp Keystone. 
---
= Obtenha ajuda com o Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A equipe de suporte da NetApp Keystone e o gerente de sucesso do Keystone (KSM) são responsáveis por fornecer serviço para suas assinaturas do Keystone. Se precisar de ajuda, entre em Contato com a equipe de suporte do Keystone.



== Suporte à NetApp Keystone

A NetApp fornece serviços operacionais remotamente aos clientes da NetApp Keystone. Esses serviços abrangem uma variedade de disciplinas operacionais nas atividades de gerenciamento de storage. Esses serviços incluem gerenciamento de ativos e configurações, gerenciamento de capacidade e desempenho, gerenciamento de alterações, gerenciamento de eventos, incidentes e problemas, atendimento de solicitações de serviço e relatórios. O NetApp demonstra um estado de controlo e provas de apoio, conforme necessário.



== Informações adicionais

A NetApp usa a solução de monitoramento ITOM para monitorar e se conetar proativamente ao ambiente NetApp Keystone para solucionar problemas.


NOTE: Em um modelo operado por parceiro, as solicitações de serviço do locatário e do sublocatário são atribuídas ao Service desk do parceiro. A ferramenta de suporte do parceiro pode ter integração com a solução ITOM.

Para obter mais informações sobre os serviços do Keystone, consulte:

* NetApp Keystone https://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* Documentação do produto NetApp https://docs.netapp.com["https://docs.netapp.com"^]




== Monitoramento do suporte do Keystone

O suporte da NetApp Keystone monitora a integridade dos produtos e dos serviços inscritos, fornece suporte remoto e colabora com o seu Gerenciador de sucesso do Keystone.

.Gerenciador de sucesso do Keystone
O Keystone Success Manager (KSM) trabalha junto com você nos serviços do Keystone e atualiza você com relatórios operacionais e de cobrança semanais ou mensais. As responsabilidades são especificadas no seu contrato NetApp Keystone.



== Gerando solicitações de serviço

Durante a integração, se você recebeu credenciais para acessar e usar o NetApp Keystone ServiceNow, poderá usar o portal para gerar solicitações de serviço para problemas relacionados às suas assinaturas do Keystone:

https://netappgssc.service-now.com/csm[]

Certifique-se de que tem os detalhes do sistema, registos e informações relacionadas prontos antes de levantar a solicitação de serviço. Quando você envia uma solicitação de serviço, a equipe de suporte do Keystone recebe o ticket de suporte e acessa as informações para solução de problemas. Você pode seguir seu ticket ServiceNow para saber o status e a resolução.

Para obter informações sobre como adicionar pacotes de suporte, link:../installation/monitor-health.html["Gerar e coletar pacote de suporte"]consulte .

Se você tiver um caso/ticket aberto que precisa ser encaminhado, envie um e-mail para um dos seguintes endereços: keystone.services@NetApp.com keystone.escalations@NetApp.com
