---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: Saiba mais sobre a cobrança do Keystone para configurações específicas, incluindo volumes clonados, proteção de dados avançada e muito mais. 
---
= Cenários diversos para faturamento do Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Compreender a cobrança do Keystone para configurações específicas pode ajudar a otimizar o uso do serviço e gerenciar custos. Os cenários incluem volumes clonados, proteção de dados avançada, volumes temporários, políticas de QoS, destinos SnapMirror, LUNs e volumes raiz/sistema.



== Faturamento de volumes clonados

Se os volumes forem clonados no ONTAP e forem usados para fazer backup e restauração de dados, você poderá continuar usando os clones sem pagamentos adicionais. No entanto, são cobrados volumes clonados usados para qualquer outra finalidade no seu negócio por uma duração extensa.

Observe o seguinte:

* Os volumes de clones estão livres do carregamento desde que o seu tamanho seja inferior a 10% do volume pai (a capacidade física usada no volume clone em comparação com a capacidade física usada no volume pai).
* Não há período de carência de 24 horas para volumes clonados, apenas o tamanho do clone é considerado.
* Uma vez que o volume do clone excede 10% do tamanho físico do pai, o clone é cobrado como um volume padrão (capacidade lógica utilizada).




== Cobrança de proteção de dados avançada

A proteção de dados avançada usa o NetApp MetroCluster para espelhar dados entre dois clusters separados fisicamente. Para agregados espelhados do MetroCluster, os dados são gravados duas vezes, uma em cada cluster. O serviço do Keystone cobra pelo consumo de cada lado de forma independente, resultando em dois Registros de consumo idênticos. Os custos adicionais são aplicados em todas as capacidades da assinatura, independentemente de os dados estarem na origem, ou se forem dados espelhados ou sem espelhamento.

Se você monitorar os clusters por meio ONTAP do Gerenciador de sistemas (System Manager) ou do Active IQ Unified Manager (Unified Manager), poderá ver uma discrepância entre o consumo informado sobre essas ferramentas e o Keystone. O System Manager e o Unified Manager não relatam volumes no cluster espelhado (remoto) e, ao fazê-lo, relatam metade das métricas de consumo relatadas pelo serviço do Keystone.

.Exemplo:
O local A e o local B são configurados em uma configuração do MetroCluster. Quando um usuário cria um volume de 10TB TB no local A, um volume idêntico de 10TB TB é criado no local B. o Keystone identifica 10TB TB de consumo em cada local, para um aumento total de 20TB TB. O System Manager e o Unified Manager relatam um volume 10TB criado no local A, mas não relatam um volume 10TB no local B..

Além disso, todos os volumes criados em um sistema Keystone com proteção de dados avançada serão contados para o consumo de proteção de dados avançada, independentemente de esses volumes estarem espelhados ou não.



== Cobrança de volumes temporários

Ocasionalmente, volumes temporários (TMP) são criados pelo ONTAP ao mover volumes. Estes volumes temporários têm uma duração curta e o consumo destes volumes não é medido para faturação.



== Políticas de faturamento e QoS adaptáveis

O Keystone mede o consumo com base nos níveis de serviço. Cada nível de serviço está associado a uma política específica de qualidade do serviço (QoS) adaptável. Durante a implantação, você será informado sobre os detalhes de cada política de QoS adaptável para os serviços do Keystone que você subscrição. Durante as operações de gerenciamento de storage, verifique se os volumes têm as políticas de QoS adaptáveis apropriadas atribuídas de acordo com os níveis de serviço inscritos, para evitar cobranças inesperadas. Para obter mais informações sobre políticas de QoS adaptáveis no ONTAP, link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Garanta a taxa de transferência com uma visão geral de QoS"^]consulte .



== Faturamento para destinos SnapMirror

O preço do volume de destino do SnapMirror é regido pela política de QoS adaptável para o nível de serviço atribuído na origem. No entanto, se a origem não tiver uma política de QoS adaptável associada, o destino será cobrado com base no nível de serviço mais baixo disponível.



== Cobrança de LUNs

Para LUNs, o mesmo padrão de faturamento é seguido como para os volumes que são governados por políticas de QoS adaptáveis. Se políticas de QoS adaptáveis separadas forem definidas em LUNs, então:

* O tamanho do LUN é contado para consumo de acordo com o nível de serviço associado desse LUN.
* O restante do espaço no volume, se houver, será cobrado de acordo com a política de QoS adaptável do nível de serviço definido no volume.




== Volumes de sistema e raiz

Os volumes de sistema e raiz são monitorados como parte do monitoramento geral do serviço Keystone, mas não são contados ou faturados. O consumo destes volumes está isento para faturação.
