---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: Saiba mais sobre a cobrança do Keystone para configurações específicas, incluindo volumes clonados, proteção de dados avançada e muito mais. 
---
= Cenários diversos para faturamento do Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Entender o faturamento do Keystone para configurações específicas pode ajudar você a otimizar o uso do serviço e gerenciar custos. As configurações incluem volumes clonados, volumes temporários, destinos SnapMirror , LUNs e volumes de sistema/raiz.



== Faturamento de volumes clonados

Se os volumes forem clonados no ONTAP e forem usados para fazer backup e restauração de dados, você poderá continuar usando os clones sem pagamentos adicionais. No entanto, são cobrados volumes clonados usados para qualquer outra finalidade no seu negócio por uma duração extensa.

Observe o seguinte:

* Os volumes de clones estão livres do carregamento desde que o seu tamanho seja inferior a 10% do volume pai (a capacidade física usada no volume clone em comparação com a capacidade física usada no volume pai).
* Não há período de carência de 24 horas para volumes clonados. Apenas o tamanho do clone é considerado.
* Uma vez que o volume do clone excede 10% do tamanho físico do pai, o clone é cobrado como um volume padrão (capacidade lógica utilizada).




== Cobrança de volumes temporários

Ocasionalmente, volumes temporários (TMP) são criados pelo ONTAP ao mover volumes. Estes volumes temporários têm uma duração curta e o consumo destes volumes não é medido para faturação.



== Faturamento para destinos SnapMirror

O preço dos volumes de destino do SnapMirror, sejam eles usados para recuperação de desastres ou retenção de longo prazo, é baseado no nível de serviço de desempenho atribuído ao destino. Não há taxa extra para proteção de dados.



== Cobrança de LUNs

Para LUNs, a cobrança é baseada nos níveis de serviço de desempenho do volume.



== Volumes de sistema e raiz

Os volumes de sistema e raiz são monitorados como parte do monitoramento geral do serviço Keystone, mas não são contados ou faturados. O consumo destes volumes está isento para faturação.
