---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: O Keystone oferece um modelo de pagamento conforme o uso para suas necessidades de consumo flexível e dimensionável. 
---
= Preços do Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O serviço de assinatura pré-pago do NetApp Keystone STaaS oferece consumo flexível e escalável com preços previsíveis e antecipados para suas necessidades de armazenamento.

A Keystone oferece os seguintes recursos de cobrança:

* Você pode pagar com base no IOPS e na capacidade comprometida de latência para atender a diversas necessidades de carga de trabalho. Os diferentes níveis de serviço de desempenho - Extreme, Premium, Standard, Value, Object e Cloud Volumes ONTAP permitem que você gerencie seu armazenamento com base no nível de serviço de desempenho adquirido.
* Ele apresenta cobrança previsível para a capacidade comprometida e pagamento por uso para uso de capacidade variável (sobrecarga).
* Você pode selecionar um preço de pacote para hardware, sistema operacional central e suporte por um preço por TIB. Você tem uma única fatura para cada tipo de armazenamento: unificado, em bloco, otimizado, de objeto ou serviços de armazenamento em nuvem.
* Você pode selecionar um prazo flexível para os serviços e opções de pagamento, como mensal, trimestral, semestral ou anual.


A cobrança do Keystone é baseada na capacidade comprometida e no consumo de sobrecarga variável.

Para obter informações sobre diferentes capacidades com suporte no Keystone, link:../concepts/supported-storage-capacity.html["Funcionalidades de storage compatíveis no Keystone"]consulte .

*Informações relacionadas*

* link:../concepts/committed-capacity-billing.html["Cobrança baseada na capacidade comprometida"]
* link:../concepts/consumed-capacity-billing.html["Medição baseada na capacidade consumida"]
* link:../concepts/burst-consumption-billing.html["Cobrança baseada no consumo de expansões sazonais"]
* link:../concepts/misc-volume-billing.html["Faturação baseada em tipos de volume diversos"]
* link:../concepts/billing-schedules.html["Horários de faturamento"]

