---
sidebar: sidebar 
permalink: concepts/pricing-v2.html 
keywords: pricing, billing introduction, Keystone billing 
summary: O Keystone oferece um modelo de pagamento conforme o uso para suas necessidades de consumo flexível e dimensionável. 
---
= Preços do Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O serviço de assinatura pré-pago do NetApp Keystone STaaS oferece consumo flexível e escalável com preços previsíveis e antecipados para suas necessidades de armazenamento.

O Keystone para a versão 2 (v2) oferece os seguintes recursos de cobrança:

* Você pode pagar com base em IOPS e latência da capacidade comprometida para atender a várias necessidades de workload. As diferentes categorias de serviço de performance: Extreme, Premium, Performance, Standard, Value e Object permitem que você gerencie seu storage com base no nível de serviço adquirido.
* Ele apresenta cobrança previsível para a capacidade comprometida e pagamento por uso para uso de capacidade variável (sobrecarga).
* Você pode selecionar um preço de pacote para hardware, sistema operacional central e suporte por um preço por TIB. Você tem uma única fatura para cada tipo de storage, arquivo, bloco, objeto ou serviços de storage de nuvem.
* Você pode selecionar um prazo flexível para os serviços e opções de pagamento, como mensal, trimestral ou anual.


A cobrança do Keystone é baseada na capacidade comprometida e no consumo de sobrecarga variável.

Para obter informações sobre diferentes capacidades com suporte no Keystone, link:../concepts/supported-storage-capacity.html["Funcionalidades de storage compatíveis no Keystone"]consulte .

*Informações relacionadas*

* link:../concepts/committed-capacity-billing-v2.html["Cobrança baseada na capacidade comprometida"]
* link:../concepts/consumed-capacity-billing-v2.html["Medição baseada na capacidade consumida"]
* link:../concepts/burst-consumption-billing-v2.html["Cobrança baseada no consumo de expansões sazonais"]
* link:../concepts/misc-volume-billing-v2.html["Faturação baseada em tipos de volume diversos"]
* link:../concepts/billing-schedules-v2.html["Horários de faturamento"]

