---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: O Keystone STaaS oferece capacidade de storage em níveis de serviço predefinidos. Cada volume gerenciado pelo Keystone está associado a um nível de serviço. 
---
= Níveis de serviço no Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O Keystone STaaS oferece capacidade de storage de dados em níveis de serviço de performance predefinidos. Cada volume gerenciado pelos serviços do Keystone está associado a um nível de serviço.

Uma assinatura pode ter vários planos de taxa e cada plano de taxa corresponde a um nível de serviço. Cada plano de tarifa tem uma capacidade comprometida por nível de serviço.

Cada nível de serviço é definido pela densidade de e/S, ou seja, IOPS/TIB/volume. Essa é a proporção de desempenho (IOPS/IOPS por segundo [IOPS]) e capacidade de storage usada (TIB), que é IOPS/TIB na latência média por volume.

Você seleciona níveis de serviço com base no ambiente de storage e nas necessidades de storage e consumo. Os níveis de serviço básicos estão disponíveis para você por padrão. Níveis de serviço específicos também estão disponíveis, se você optou por serviços adicionais. Por exemplo, para o serviço complementar avançado de proteção de dados, o nível de serviço _Advanced Data-Protect_ é atribuído à sua assinatura.


TIP: Está disponível uma descrição detalhada do serviço para os níveis de serviço STaaS do NetApp Keystone https://www.netapp.com/services/keystone/terms-and-conditions/["aqui"^] .

Os níveis de serviço básicos para os tipos de storage compatíveis, arquivo, bloco, objeto e serviços de nuvem são descritos nas seções a seguir:



== Níveis de serviço para storage de arquivos e blocos

*Protocolos compatíveis*: NFS, CIFS, iSCSI e FC

|===


| *Nível de serviço* | *Extreme* | *Premium* | *Desempenho* | *Standard* | *Valor* 


| *Tipos de carga de trabalho de amostra* | Análises, bancos de dados, aplicativos de missão crítica | VDI, VSI, desenvolvimento de software | OLTP, OLAP, contêineres, desenvolvimento de software | Compartilhamentos de arquivo, servidores da Web | Backup 


| *Máximo de IOPS/Tibs lógicos armazenados por volume* | 12.288 | 4.096 | 2.048 | 512 | 128 


| *Máximo de IOPS/Tibs lógicos alocados por volume* | 6.144 | 2.048 | 1.024 | 256 | 64 


| * Máximo de Mbps/Tibs lógicos armazenados por volume a 32K B/S* | 384 | 128 | 64 | 16 | 4 


| * Target 90.o percentil latência* | menos de 1 ms | menos de 2 ms | menos de 4 ms | menos de 4 ms | menos de 17 ms 


| * Tamanho do bloco* 5+| 32K 
|===


=== Mais sobre níveis de serviço para storage de arquivos e blocos

As métricas de nível de serviço básico dependem das seguintes condições:

* Os níveis de serviço para storage de arquivo e bloco são compatíveis com o ONTAP 9.7 e posterior.
* Os valores de IOPS/TIB/volume, Mbps/TIB/volume e latência para níveis de serviço baseiam-se na quantidade de dados armazenados no volume, no tamanho de bloco de 32KB U e em uma combinação aleatória de operações de e/S de 70% de leitura e 30% de gravação.
* IOPS/TIB/volume reais e Mbps/TIB/volume podem variar com base no tamanho do bloco real ou assumido, na simultaneidade da carga de trabalho do sistema ou nas operações de entrada/saída.
* A latência não inclui o seguinte:
+
** latência do aplicativo ou do host
** latência de rede do cliente de ou para as portas do controlador
** Overheads associados à transferência de dados para o armazenamento de objetos em caso de FabricPool
** Latência aplicada automaticamente pelo QoS para manter a e/S dentro dos máximos do nível de serviço


* Os valores de latência não se aplicam às operações de gravação do MetroCluster. Essas operações de gravação dependem da distância dos sistemas remotos.
* Se um ou mais volumes em um sistema de armazenamento não tiverem uma política AQoS atribuída, esses volumes serão considerados como volumes não compatíveis e nenhum nível de serviço desejado será aplicável a esses sistemas.
* _IOPS_ esperado é direcionado para o FabricPool somente se a política de disposição em camadas estiver definida como "nenhum" e nenhum bloco estiver na nuvem. _IOPS_ esperado é destinado a volumes que não estão em uma relação síncrona do SnapMirror.
* As operações de IO do workload precisam ser balanceadas em todos os controladores implantados, conforme determinado pelo pedido do Keystone.




== Storage de objetos

*Protocolo suportado*: S3

|===


| *Nível de serviço* | Objeto 


| *Tipo de carga de trabalho* | Repositório de Mídia, arquivamento 


| *Máximo de IOPS/TIB lógico armazenado por volume* | N/A. 


| *Máximo de Mbps/TIB lógico armazenado por volume* | N/A. 


| *Latência média* | N/A. 
|===

NOTE: A latência não inclui overheads associados à transferência de dados para o armazenamento de objetos no caso de armazenamento FabricPool.



== Storage de nuvem

*Protocolo compatível*: NFS, CIFS, iSCSI e S3 (somente AWS e Azure)

|===


| *Nível de serviço* | Cloud Volumes ONTAP 


| *Tipo de carga de trabalho* | Recuperação de desastres, desenvolvimento/teste de software, aplicativos de negócios 


| *Máximo de IOPS/TIB lógico armazenado por volume* | N/A. 


| *Máximo de Mbps/TIB lógico armazenado por volume* | N/A. 


| *Latência média* | N/A. 
|===
[NOTE]
====
* Serviços nativos em nuvem, como computação, storage, rede, são faturados por fornecedores de nuvem.
* Esses serviços dependem das características de computação e storage de nuvem.


====
*Informações relacionadas*

* link:../concepts/supported-storage-capacity.html["Capacidades de armazenamento suportadas"]
* link:..//concepts/metrics.html["Métricas e definições usadas nos Serviços do Keystone"]
* link:../concepts/qos.html["Qualidade do serviço (QoS) no Keystone"]
* link:../concepts/pricing.html["Preços do Keystone"]

