---
sidebar: sidebar 
permalink: concepts/service-levels-v2.html 
keywords: service levels, service level, rate plan or service level 
summary: O Keystone STaaS oferece capacidade de storage em níveis de serviço predefinidos. Cada volume gerenciado pelo Keystone está associado a um nível de serviço. 
---
= Níveis de serviço de desempenho em Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O Keystone STaaS para versão 2 (v2) oferece capacidade de armazenamento de dados em níveis de serviço de desempenho predefinidos. Cada volume gerenciado pelos serviços Keystone está associado a um nível de serviço de desempenho.

Uma assinatura pode ter vários planos de tarifas, e cada plano corresponde a um nível de serviço de desempenho. Cada plano de tarifas tem uma capacidade comprometida por nível de serviço de desempenho.

Cada nível de serviço de desempenho é definido por sua densidade de E/S, ou seja, IOPS/TiB/volume. Essa é a proporção de desempenho (IOPS/IOPS por segundo [IOPS]) e capacidade de storage usada (TIB), que é IOPS/TIB na latência média por volume.

Você seleciona os níveis de serviço de desempenho com base no seu ambiente de armazenamento e nas suas necessidades de armazenamento e consumo. Os níveis de serviço de desempenho básicos estão disponíveis por padrão. Níveis de serviço de desempenho específicos também estão disponíveis, caso você tenha optado por serviços complementares. Por exemplo, para o serviço complementar de proteção de dados avançada, o nível de serviço de desempenho _Advanced Data-Protect_ é atribuído à sua assinatura.


TIP: Uma descrição detalhada do serviço para os níveis de serviço de desempenho do NetApp Keystone STaaS está disponível  https://www.netapp.com/services/keystone/terms-and-conditions/["aqui"^] .

Os níveis de serviço de desempenho básico para os tipos de armazenamento suportados, arquivo, bloco, objeto e serviços de nuvem são descritos nas seções a seguir:



== Níveis de serviço de desempenho para armazenamento de arquivos e blocos

*Protocolos compatíveis*: NFS, CIFS, iSCSI e FC

|===


| *Nível de serviço de desempenho* | *Extreme* | *Premium* | *Desempenho* | *Standard* | *Valor* 


| *Tipos de carga de trabalho de amostra* | Análises, bancos de dados, aplicativos de missão crítica | VDI, VSI, desenvolvimento de software | OLTP, OLAP, contêineres, desenvolvimento de software | Compartilhamentos de arquivo, servidores da Web | Backup 


| *Máximo de IOPS/Tibs lógicos armazenados por volume* | 12.288 | 4.096 | 2.048 | 512 | 128 


| *Máximo de IOPS/Tibs lógicos alocados por volume* | 6.144 | 2.048 | 1.024 | 256 | 64 


| * Máximo de Mbps/Tibs lógicos armazenados por volume a 32K B/S* | 384 | 128 | 64 | 16 | 4 


| * Target 90.o percentil latência* | menos de 1 ms | menos de 2 ms | menos de 4 ms | menos de 4 ms | menos de 17 ms 


| * Tamanho do bloco* 5+| 32K 


| * Tipo de capacidade comprometida e mensurada* 5+| Lógico 
|===


=== Mais sobre níveis de serviço de desempenho para armazenamento de arquivos e blocos

As métricas de nível de serviço de desempenho básico dependem das seguintes condições:

* Os níveis de serviço de desempenho para armazenamento de arquivos e blocos são compatíveis com ONTAP 9.7 e posteriores.
* Os valores de IOPS/TiB/volume, MBps/TiB/volume e latência para níveis de serviço de desempenho são baseados na quantidade de dados armazenados no volume, no tamanho do bloco de 32 KB e em uma combinação aleatória de 70% de operações de E/S de leitura e 30% de gravação.
* IOPS/TIB/volume reais e Mbps/TIB/volume podem variar com base no tamanho do bloco real ou assumido, na simultaneidade da carga de trabalho do sistema ou nas operações de entrada/saída.
* A latência não inclui o seguinte:
+
** latência do aplicativo ou do host
** latência de rede do cliente de ou para as portas do controlador
** Overheads associados à transferência de dados para o armazenamento de objetos em caso de FabricPool
** latência aplicada automaticamente pelo QoS para manter o IO dentro dos níveis máximos de serviço de desempenho


* Os valores de latência não se aplicam às operações de gravação do MetroCluster. Essas operações de gravação dependem da distância dos sistemas remotos.
* Se um ou mais volumes em um sistema de armazenamento não tiverem uma política de AQoS atribuída, esses volumes serão considerados volumes não compatíveis e nenhum nível de serviço de desempenho de destino será aplicável a esses sistemas.
* _IOPS_ esperado é direcionado para o FabricPool somente se a política de disposição em camadas estiver definida como "nenhum" e nenhum bloco estiver na nuvem. _IOPS_ esperado é destinado a volumes que não estão em uma relação síncrona do SnapMirror.
* As operações de IO do workload precisam ser balanceadas em todos os controladores implantados, conforme determinado pelo pedido do Keystone.




== Storage de objetos

*Protocolo suportado*: S3

|===


| *Nível de serviço de desempenho* | Objeto 


| *Tipo de carga de trabalho* | Repositório de Mídia, arquivamento 


| *Máximo de IOPS/TIB lógico armazenado por volume* | N/A. 


| *Máximo de Mbps/TIB lógico armazenado por volume* | N/A. 


| *Latência média* | N/A. 


| * Tipo de capacidade comprometida e mensurada* | Físico 
|===

NOTE: A latência não inclui overheads associados à transferência de dados para o armazenamento de objetos no caso de armazenamento FabricPool.



== Storage de nuvem

*Protocolo compatível*: NFS, CIFS, iSCSI e S3 (somente AWS e Azure)

|===


| *Nível de serviço de desempenho* | Cloud Volumes ONTAP 


| *Tipo de carga de trabalho* | Recuperação de desastres, desenvolvimento/teste de software, aplicativos de negócios 


| *Máximo de IOPS/TIB lógico armazenado por volume* | N/A. 


| *Máximo de Mbps/TIB lógico armazenado por volume* | N/A. 


| *Latência média* | N/A. 
|===
[NOTE]
====
* Serviços nativos em nuvem, como computação, storage, rede, são faturados por fornecedores de nuvem.
* Esses serviços dependem das características de computação e storage de nuvem.


====
*Informações relacionadas*

* link:../concepts/supported-storage-capacity-v2.html["Capacidades de armazenamento suportadas"]
* link:..//concepts/metrics-v2.html["Métricas e definições usadas nos Serviços do Keystone"]
* link:../concepts/qos.html["Qualidade do serviço (QoS) no Keystone"]
* link:../concepts/pricing-v2.html["Preços do Keystone"]

