---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Saiba mais sobre os tipos de capacidades de armazenamento suportados pelo serviço NetApp Keystone STaaS para a versão 3. 
---
= Funcionalidades de storage compatíveis no Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O serviço NetApp Keystone STaaS suporta vários tipos de capacidades de armazenamento. Entender esses diferentes termos de capacidade pode ajudar você a usar o Keystone.



== Capacidade lógica

Esta é a quantidade de capacidade de armazenamento necessária para armazenar dados do usuário antes que qualquer eficiência de dados fornecida pelo conjunto de armazenamento seja aplicada.



== Capacidade comprometida

A capacidade lógica mínima cobrada mensalmente durante a assinatura:

* A capacidade é comprometida com cada nível de serviço de desempenho.
* Capacidade comprometida e níveis adicionais de serviço de desempenho podem ser adicionados durante o prazo.




=== Mudanças na capacidade comprometida

Durante o período de vigência de uma assinatura, você pode alterar as capacidades comprometidas. No entanto, existem certas condições prévias:

* A capacidade comprometida pode ser reduzida com base em certas condições. Para obter informações, link:../concepts/capacity-requirements.html["Redução de capacidade"]consulte .
* A capacidade comprometida não pode ser aumentada 90 dias antes do término da assinatura, a menos que a assinatura seja renovada por um período adicional de 12 meses.
* Você pode solicitar alterações na capacidade comprometida por meio do Console ou do seu Keystone Success Manager (KSM). Para obter informações sobre como solicitar alterações, consultelink:../concepts/gssc.html["Suporte à NetApp Keystone"] .




== Capacidade consumida

A capacidade consumida refere-se à capacidade (em TIB de armazenamento) atualmente consumida no serviço. Ele é calculado de forma diferente com base no tipo de armazenamento:

* *Armazenamento unificado ou otimizado em bloco*: A capacidade consumida é calculada com base no tipo de capacidade (lógica ou física) selecionada durante o processo de pedido.  O cálculo é realizado por instância de nível de serviço de desempenho.
+
.. *Capacidade lógica*: É a soma de:
+
*** Capacidade lógica medida, antes da eficiência dos dados do array de armazenamento, para armazenar todas as instâncias e tipos de dados do cliente, como cópias, cópias espelhadas, versões e clones.
*** Capacidade física usada para armazenar metadados e dados diferenciais de snapshots e certos clones.
*** Qualquer capacidade física com provisionamento espesso.


.. *Capacidade física*: É a soma de:
+
*** Capacidade física medida, após eficiências de dados do array de armazenamento, para armazenar todas as instâncias e tipos de dados do cliente, como cópias, cópias espelhadas, versões e clones.
*** Capacidade física usada para armazenar metadados e dados diferenciais de snapshots.
*** Qualquer capacidade física com provisionamento espesso.




* *Armazenamento de objetos*: A capacidade consumida é calculada como a quantidade de capacidade física medida usada para armazenar todas as instâncias e tipos de dados do cliente em todos os nós. Este cálculo é baseado nas políticas de gerenciamento do ciclo de vida da informação (ILM) configuradas.
* *Cloud Volumes ONTAP*: A capacidade consumida é calculada como a quantidade de capacidade provisionada medida de todos os volumes Cloud Volumes ONTAP.




== Capacidade de pico sazonal

O serviço NetApp Keystone STaaS permite que você use capacidade adicional além da capacidade comprometida para um nível de serviço de desempenho. Isso é conhecido como uso de capacidade máxima.

Observe estes pontos:

* Capacidade de pico sazonal é acordada no contrato do Keystone. Geralmente, ele é definido até 20% acima da capacidade comprometida, por instância de nível de serviço de desempenho, com opções adicionais disponíveis para selecionar limites de capacidade de pico de 40% ou 60% da capacidade comprometida.
* O consumo de capacidade de pico é faturado na mesma taxa que a capacidade comprometida correspondente ao nível de serviço de desempenho selecionado.
* Os serviços STaaS da Keystone oferecem um período de isenção de 60 dias a partir da data de início.




== Capacidade faturada

Cobrança mensal (capacidade comprometida [TIB] * taxa comprometida [ USD/TIB]) (capacidade de sobrecarga provisionada média diária [TIB] * taxa de explosão [ USD/TIB]). A fatura mensal contém um custo mínimo com base na capacidade comprometida.

A fatura mensal varia além da cobrança mínima com base no consumo médio diário de capacidade de pico sazonal.
