---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Saiba mais sobre os tipos de capacidades de armazenamento suportados pelo serviço NetApp Keystone STaaS para a versão 3. 
---
= Tipos de capacidade de storage em Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS utiliza diversos termos de capacidade para medir, comprometer e faturar o storage. Compreender esses termos ajudará você a planejar sua assinatura e interpretar seus relatórios de uso e faturas.



== Capacidade lógica

Esta é a quantidade de capacidade de armazenamento necessária para armazenar dados do usuário antes que qualquer eficiência de dados fornecida pelo conjunto de armazenamento seja aplicada.



== Capacidade comprometida

A capacidade lógica mínima cobrada mensalmente durante a assinatura:

* A capacidade é comprometida para cada instância de nível de serviço de desempenho para storage unificado ou otimizado para blocos, ou por cluster AFX.
* Capacidade comprometida e níveis adicionais de serviço de desempenho podem ser adicionados durante o prazo.




=== Mudanças na capacidade comprometida

Durante a assinatura, você pode alterar as capacidades contratadas, sujeitas a determinadas condições. Para obter detalhes completos sobre as regras de aumento e redução de capacidade, consulte link:../concepts/capacity-requirements.html["Requisitos de capacidade para os níveis de serviço de desempenho do Keystone"]. Para solicitar uma alteração, entre em contato com seu Keystone Success Manager (KSM) ou link:../concepts/support-services.html["NetApp suporte"].



== Capacidade consumida

A capacidade consumida refere-se à capacidade (em TiB de storage) atualmente utilizada pelo serviço. Ela é calculada de forma diferente dependendo do tipo de storage de dados:

* *Armazenamento unificado ou otimizado em bloco*: A capacidade consumida é calculada com base no tipo de capacidade (lógica ou física) selecionada durante o processo de pedido.  O cálculo é realizado por instância de nível de serviço de desempenho.
+
.. *Capacidade lógica*: É a soma de:
+
*** Capacidade lógica medida, antes da eficiência dos dados do array de armazenamento, para armazenar todas as instâncias e tipos de dados do cliente, como cópias, cópias espelhadas, versões e clones.
*** Capacidade física usada para armazenar metadados e dados diferenciais de snapshots e certos clones.
*** Qualquer capacidade física com provisionamento espesso.


.. *Capacidade física*: É a soma de:
+
*** Capacidade física medida, após eficiências de dados do array de storage, para armazenar todas as instâncias e tipos de dados do cliente, como cópias, cópias espelhadas, versões e clones.
*** Capacidade física usada para armazenar metadados e dados diferenciais de snapshots.
*** Qualquer capacidade física com provisionamento espesso.




* *Armazenamento AFX*: é calculado por cluster AFX como a soma de:
+
** Capacidade física medida, após eficiências de dados do array de storage, para armazenar todas as instâncias e tipos de dados do cliente, como cópias, cópias espelhadas, versões e clones.
** Capacidade física usada para armazenar metadados e dados diferenciais de snapshots.
** Qualquer capacidade física com provisionamento espesso.


* *Armazenamento de objetos*: A capacidade consumida é calculada como a quantidade de capacidade física medida usada para armazenar todas as instâncias e tipos de dados do cliente em todos os nós. Este cálculo é baseado nas políticas de gerenciamento do ciclo de vida da informação (ILM) configuradas.
* *Cloud Volumes ONTAP*: A capacidade consumida é calculada como a quantidade de capacidade lógica provisionada medida de todos os volumes do Cloud Volumes ONTAP.




== Capacidade de pico sazonal

O serviço NetApp Keystone STaaS permite que você use capacidade adicional além da capacidade comprometida para um nível de serviço de desempenho. Isso é conhecido como uso de capacidade máxima.

Observe estes pontos:

* O limite de capacidade de burst é acordado no pedido do Keystone. Normalmente, é definido por padrão como 20% acima da capacidade contratada por instância de nível de serviço de desempenho ou por cluster AFX, com opções adicionais disponíveis para storage unificado e otimizado para blocos, permitindo selecionar limites de capacidade de burst de 40% ou 60% da capacidade contratada.
* O consumo de capacidade em picos de uso é faturado à mesma taxa da capacidade contratada correspondente ao tipo de storage de dados (DST) e nível de serviço de desempenho selecionado.
* Os serviços STaaS da Keystone oferecem um período de isenção de 60 dias a partir da data de início.




== Capacidade faturada

Cobrança mensal (capacidade comprometida [TIB] * taxa comprometida [ USD/TIB]) (capacidade de sobrecarga provisionada média diária [TIB] * taxa de explosão [ USD/TIB]). A fatura mensal contém um custo mínimo com base na capacidade comprometida.

A fatura mensal varia além da cobrança mínima com base no consumo médio diário de capacidade de pico sazonal.
