---
sidebar: sidebar 
permalink: concepts/support-services.html 
keywords: Keystone support, service request, support ticket 
summary: Utilize o site de suporte da NetApp para criar uma solicitação de suporte ou encontrar informações de contato para suas assinaturas da Keystone. 
---
= Obtenha ajuda com o Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp fornece serviços operacionais aos clientes Keystone. Os clientes recebem um Keystone Success Manager (KSM) dedicado, opções de contato direto para suporte e monitoramento proativo por meio da solução ITOM.



== Serviços de suporte da NetApp

NetApp fornece serviços operacionais remotamente aos clientes Keystone. Esses serviços abrangem uma gama de atividades de gerenciamento de storage, incluindo gerenciamento de ativos e configuração, gerenciamento de capacidade e desempenho, gerenciamento de mudanças, gerenciamento de eventos e incidentes, atendimento de solicitações de serviço e geração de relatórios.

.Gerenciador de sucesso do Keystone
Seu KSM trabalha em estreita colaboração com você em seus serviços Keystone e fornece relatórios operacionais e de faturamento semanais ou mensais. As responsabilidades específicas são definidas em seu acordo Keystone da NetApp.



== Contate o suporte

Se você tiver algum problema com sua assinatura Keystone, faça login no link:https://support.netapp.com["NetApp site de suporte"^] usando suas credenciais NSS para criar um chamado de suporte.

Caso não possua um login NSS, link:https://mysupport.netapp.com/site/user/registration["Registre sua conta"^] utilize o número de série (SN) de um dos nós da sua assinatura.

Para obter instruções passo a passo com capturas de tela, consulte link:https://kb.netapp.com/nss/Support_Site/How_to_open_a_technical_support_case["Como abrir um caso de suporte técnico"^].

Se preferir falar diretamente com um representante de suporte, ligue para um dos seguintes números:

* EUA / Canadá: 888 463 8277
* Europa: 00 800 44 638277
* Índia: 000 800 100 8948
* Mais números globais: link:https://www.netapp.com/company/contact-us/support/["https://www.netapp.com/company/contact-us/support/"^]




== Monitoramento de suporte

NetApp usa a solução de monitoramento ITOM para monitorar proativamente a integridade de seus produtos e serviços assinados e se conectar ao ambiente NetApp Keystone para solução de problemas.



== Recursos adicionais

Para obter mais informações sobre os serviços do Keystone, consulte:

* link:https://www.netapp.com/us/solutions/keystone/index.aspx["NetApp Keystone"^]
* link:https://docs.netapp.com["Documentação de produtos da NetApp"^]


*Informações relacionadas*

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_Identify_Serial_Number_of_ONTAP_Platform["Como identificar o número de série da plataforma ONTAP"^]
* link:https://kb.netapp.com/hybrid/StorageGRID/Maintenance/Which_serial_number_to_use_when_creating_StorageGRID_technical_support_case["Qual número de série usar ao criar um chamado de suporte técnico para o StorageGRID"^]

