---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Os serviços Keystone STaaS são compatíveis com ONTAP e StorageGRID. 
---
= Storage compatível no Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O serviço Keystone STaaS oferece suporte ao armazenamento unificado, otimizado por bloco e de objetos do NetApp e do Cloud Volumes ONTAP.

As opções de armazenamento suportadas são:

* *Armazenamento unificado*: Inclui armazenamento de arquivos, blocos e objetos S3, disponível nos sistemas NetApp ONTAP AFF e FAS.
* *Armazenamento otimizado em bloco*: Inclui armazenamento em bloco disponível em sistemas NetApp ONTAP ASA .
* *Armazenamento de objetos*: Inclui armazenamento de objetos disponível em sistemas NetApp StorageGRID.


O Keystone STaaS fornece serviços padrão e opcionais para o seu storage.

*Serviços padrão Keystone STaaS*: Os serviços padrão estão incluídos na assinatura básica e não são cobrados separadamente.

*Serviços complementares do Keystone STaaS*: São serviços opcionais e cobráveis que fornecem utilitários e benefícios adicionais além dos serviços de assinatura padrão do Keystone STaaS.

Os serviços Keystone STaaS podem ser usados simultaneamente. Por exemplo, uma assinatura de armazenamento em nuvem pode ter o mesmo prazo que as assinaturas unificadas, otimizadas para blocos e de armazenamento de objetos. Um serviço de nuvem pode ser incluído a qualquer momento durante o período de serviço de uma subscrição de storage existente. No entanto, se você não planeja renovar uma assinatura unificada, otimizada para blocos ou de armazenamento de objetos existente, uma assinatura de armazenamento em nuvem não poderá ser adicionada durante os últimos 90 dias da assinatura.



== Serviços para armazenamento unificado, otimizado por bloco e de objetos

Os serviços Keystone STaaS para armazenamento unificado, otimizado por blocos e de objetos oferecem suporte a vários recursos e protocolos e são descritos na tabela a seguir:

|===
| Armazenamento | Plataforma | Protocolos | Recursos suportados 


 a| 
Storage unificado
 a| 
ONTAP
 a| 
NFS e CIFS
 a| 
Suporta todos os recursos do ONTAP One



 a| 
Armazenamento otimizado em bloco
 a| 
ONTAP
 a| 
FC e iSCSI
 a| 
Suporta todos os recursos do ONTAP One



 a| 
Storage de objetos
 a| 
StorageGRID
 a| 
S3
 a| 
Suporta todos os recursos do ONTAP One

|===
Para saber mais sobre o ONTAP One, consulte link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Visão geral do licenciamento do ONTAP"^] e link:https://www.netapp.com/blog/ontap-one/["ONTAP One: todo o poder do ONTAP, agora tudo em um"^] .



== Serviços para armazenamento em nuvem

O Keystone STaaS fornece serviços de storage de nuvem. O Keystone STaaS oferece suporte aos recursos de gerenciamento de dados do Cloud Volumes ONTAP no Amazon Web Services (AWS), no Microsoft Azure e no Google Cloud Platform.


NOTE: Os serviços de computação, storage e rede baseados em Hyperscalar exigidos pelo Cloud Volumes ONTAP não são fornecidos pelo NetApp como parte das assinaturas do Keystone STaaS. Essas assinaturas precisam ser obtidas diretamente de fornecedores de serviços de nuvem em hyperscalar.
