---
sidebar: sidebar 
permalink: concepts/uscs.html 
keywords: netapp, keystone, US citizen support, USCS GSSC, Keystone Success Manager, USCS support 
summary: O apoio ao Cidadão dos Estados Unidos é um serviço complementar que fornece a entrega e o apoio de serviços contínuos do Keystone de cidadãos dos EUA em solo dos EUA. 
---
= Saiba mais sobre USCS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O suporte ao Cidadão dos Estados Unidos (USCS) é uma oferta adicional para assinaturas do NetApp Keystone. Ele permite que você receba entrega e suporte de serviços Keystone contínuos de cidadãos dos EUA em solo dos EUA.

Leia as seções a seguir para entender quais elementos de suas assinaturas estão vinculados a esse serviço complementar e são fornecidos sob os termos do Contrato NetApp Keystone.nota de rodapé:disclaimer1[os serviços e ofertas descritos aqui estão sujeitos a, e limitados e regidos por um Contrato Keystone totalmente executado.]



== Monitoramento do Centro de suporte de Serviços globais da NetApp

O Centro Global de Serviços e suporte (GSSC) da NetApp monitora a integridade dos seus produtos e serviços inscritos, fornece suporte remoto e colabora com o seu gerente de sucesso do Keystone. Todos os funcionários que monitoram os produtos associados aos pedidos de assinatura relevantes do Keystone são cidadãos dos EUA que operam em solo dos EUA.



== Gerenciador de sucesso do Keystone

O Keystone Success Manager (KSM) é um cidadão dos EUA que opera em solo americano. Suas responsabilidades são especificadas no seu Contrato NetApp Keystone.



== Atividades de implantação

Quando disponíveis, as atividades de implantação e instalação no local e remota são conduzidas por cidadãos dos EUA em solo dos EUA. Nota de rodapé:isenção de responsabilidade[a disponibilidade de pessoal apropriado para atividades no local depende da localização geográfica em que os sistemas Keystone são implantados.]



== Suporte

Quando disponíveis, as atividades necessárias de solução de problemas e suporte no local são conduzidas por cidadãos dos EUA em solo dos EUA.
