---
sidebar: sidebar 
permalink: concepts/usps-v2.html 
keywords: netapp, keystone, US citizen support, USPS, Keystone Success Manager, USPS support 
summary: O United States Protected Support é um serviço complementar que fornece fornecimento e suporte de serviços Keystone contínuos de cidadãos dos EUA em solo norte-americano. 
---
= Saiba mais sobre USPS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O suporte protegido dos Estados Unidos (USPS) é uma oferta complementar para assinaturas do NetApp Keystone. Ele permite que você receba entrega e suporte de serviços Keystone contínuos de cidadãos dos EUA em solo dos EUA.

Leia as seções a seguir para entender quais elementos de suas assinaturas estão vinculados a esse serviço complementar e são fornecidos sob os termos do Contrato NetApp Keystone.nota de rodapé:disclaimer1[os serviços e ofertas descritos aqui estão sujeitos a, e limitados e regidos por um Contrato Keystone totalmente executado.]



== Monitoramento NetApp USPS

A equipe de suporte do Keystone, USPS NetApp monitora a integridade dos seus produtos e serviços inscritos, fornece suporte remoto e colabora com o seu Gerenciador de sucesso do Keystone. Todos os funcionários que monitoram os produtos associados aos pedidos de assinatura relevantes do Keystone são cidadãos dos EUA que operam em solo dos EUA.



== Gerenciador de sucesso do Keystone

O Keystone Success Manager (KSM) é um cidadão dos EUA que opera em solo americano. Suas responsabilidades são especificadas no seu Contrato NetApp Keystone.



== Atividades de implantação

Quando disponíveis, as atividades de implantação e instalação no local e remota são conduzidas por cidadãos dos EUA em solo dos EUA. Nota de rodapé:isenção de responsabilidade[a disponibilidade de pessoal apropriado para atividades no local depende da localização geográfica em que os sistemas Keystone são implantados.]



== Suporte

Quando disponíveis, as atividades necessárias de solução de problemas e suporte no local são conduzidas por cidadãos dos EUA em solo dos EUA.
