---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: Instale o software Keystone Collector a partir do repositório de software YUM. 
---
= Instale o Keystone Collector em sistemas Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode instalar o software Keystone Collector em um servidor Linux usando um RPM ou um pacote Debian. Siga as etapas de instalação, dependendo da sua distribuição Linux.

[role="tabbed-block"]
====
.Usando RPM
--
. SSH para o servidor Keystone Collector e elevar-se a `root` privilégios.
. Importe a assinatura pública da Keystone :
`# rpm --import https://keystone.netapp.com/repo1/RPM-GPG-NetApp-Keystone-20251020`
. Certifique-se de que o certificado público correto foi importado, verificando a impressão digital da plataforma Keystone Billing no banco de dados RPM:
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` A impressão digital correta tem esta aparência:
`9297 0DB6 0867 22E7 7646 E400 4493 5CBB C9E9 FEDC`
. Baixe o `keystonerepo.rpm` arquivo:
`curl -O https://keystone.netapp.com/repo1/keystonerepo.rpm`
. Verifique a autenticidade do arquivo:
`rpm --checksig -v keystonerepo.rpm` A assinatura de um arquivo autêntico tem a seguinte aparência:
`Header V4 RSA/SHA512 Signature, key ID c9e9fedc: OK`
. Instale o arquivo do repositório de software DO YUM:
`# yum install keystonerepo.rpm`
. Quando o repositório Keystone estiver instalado, instale o pacote keystone-collector por meio do gerenciador de pacotes YUM:
+
`# yum install keystone-collector`

+
Para o Red Hat Enterprise Linux 9, execute o seguinte comando para instalar o pacote keystone-collector: 
`# yum install keystone-collector-rhel9`



--
.Usando Debian
--
. SSH para o servidor Keystone Collector e elevar-se a `root` privilégios.
`sudo su`
. Transfira o `keystone-sw-repo.deb` ficheiro:
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Instale o arquivo de repositório de software do Keystone:
`# dpkg -i keystone-sw-repo.deb`
. Atualize a lista de pacotes:
`# apt-get update`
. Quando o Keystone repo estiver instalado, instale o pacote keystone-Collector:
`# apt-get install keystone-collector`


--
====

NOTE: Ao concluir a instalação, você pode usar o utilitário Keystone Collector Management Terminal User Interface (TUI) para executar as atividades de configuração e monitoramento. Você pode usar vários controles de teclado, como as teclas Enter e seta, para selecionar as opções e navegar por esta TUI. link:../installation/configuration.html["Configure o Keystone Collector"]Consulte e link:../installation/monitor-health.html["Monitorar a integridade do sistema"] para obter informações.
