---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Identificar problemas conhecidos que podem impedir que você use os serviços de assinatura do Keystone de forma eficaz. 
---
= Problemas conhecidos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Identificar problemas conhecidos que podem impedir que você use os serviços de assinatura do Keystone de forma eficaz.

Os seguintes problemas conhecidos são relatados no NetApp Keystone STaaS:

[cols="3*"]
|===
| Problema conhecido | Descrição | Solução alternativa 


 a| 
Detalhes do volume indisponíveis para subscrições primárias e vinculadas
 a| 
A guia *Resumo de volume* mostra zero para o número total de volumes, status de conformidade de QoS, contagem de volumes protegidos e capacidade total consumida para assinaturas secundárias primárias e vinculadas.
 a| 
Nenhum



 a| 
Não é possível gerar relatórios para assinaturas
 a| 
Quando mais de 10-12 assinaturas são selecionadas na guia *assinaturas* na página *assinaturas do Keystone*, o relatório não consegue gerar ao clicar no botão *Download CSV* com a opção *incluir dados para cada nível de serviço*.
 a| 
Nenhum

|===