---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Identificar problemas conhecidos que podem impedir que você use os serviços de assinatura do Keystone de forma eficaz. 
---
= Problemas conhecidos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Identificar problemas conhecidos que podem impedir que você use os serviços de assinatura do Keystone de forma eficaz.

Os seguintes problemas conhecidos são relatados no NetApp Keystone STaaS:

[cols="3*"]
|===
| Problema conhecido | Descrição | Solução alternativa 


 a| 
Exibição incorreta do tipo de política de QoS
 a| 
Na guia *Detalhes do volume*, a coluna *tipo de política de QoS* exibe _QoS_ quando nenhuma política de QoS é aplicada e a coluna compatível mostra _não definido_, causando uma inconsistência no status da política de QoS exibida.
 a| 
Nenhum



 a| 
Detalhes do volume indisponíveis para subscrições primárias e vinculadas
 a| 
A guia *Resumo de volume* mostra zero para o número total de volumes, status de conformidade de QoS, contagem de volumes protegidos e capacidade total consumida para assinaturas secundárias primárias e vinculadas.
 a| 
Nenhum

|===