---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Problemas conhecidos identificam problemas que podem impedir você de usar o Keystone de forma eficaz. 
---
= Problemas conhecidos no Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Problemas conhecidos identificam problemas que podem impedir você de usar o Keystone STaaS de forma eficaz.

Os seguintes problemas conhecidos são relatados no NetApp Keystone STaaS:

[cols="3*"]
|===
| Problema conhecido | Descrição | Solução alternativa 


 a| 
Tendência de queda imprecisa nos dados de previsão de consumo
 a| 
Na aba *Tendência de consumo*, quando a opção *Previsão* está ativada na visualização *Consumo histórico*, a utilização de capacidade projetada mostra uma tendência de queda significativa e imprecisa.
 a| 
Nenhum



 a| 
Modificar assinatura indisponível
 a| 
A opção para modificar a capacidade comprometida para assinaturas do Keystone está atualmente indisponível no NetApp Console. Essa funcionalidade será reintroduzida em uma versão futura.
 a| 
Nenhum



 a| 
Fatura incorreta devido a incompatibilidade de dados
 a| 
Uma incompatibilidade nos dados de consumo das assinaturas do AutoSupport leva à geração de faturas incorretas, causando imprecisões de faturamento.
 a| 
Nenhum



 a| 
Exibição incorreta do tipo de política de QoS
 a| 
Na guia *Detalhes do volume*, a coluna *tipo de política de QoS* exibe _QoS_ quando nenhuma política de QoS é aplicada e a coluna compatível mostra _não definido_, causando uma inconsistência no status da política de QoS exibida.
 a| 
Nenhum



 a| 
Detalhes do volume indisponíveis para subscrições primárias e vinculadas
 a| 
A guia *Resumo de volume* mostra zero para o número total de volumes, status de conformidade de QoS, contagem de volumes protegidos e capacidade total consumida para assinaturas secundárias primárias e vinculadas.
 a| 
Nenhum

|===